### PR TITLE
just wrap decodeURIComponent in try catch (#1)

### PR DESCRIPTION
**Pull request by Bullewinkle**
it is related to this
https://github.com/ben-eb/postcss-svgo/pull/24

### CODE REVIEW

**Comment by Bullewinkle** [comment]
this is works for me, if i do wrong - please, explain.

**Comment by ben-eb** [comment]
Can we handle this case instead of silently failing? Also, this pull request is missing a test case for this behaviour.

**Comment by Bullewinkle** [comment]
Yes, i think. If just replace all "%" in svg-string with "%25" (without try catch) thing go right. What do you think?

**Comment by ben-eb** [comment]
Sounds good to me. 👍

**Comment by ben-eb** [comment]
@Bullewinkle Did you get anywhere with this? 😄

**Pull request closed without merging**
